discord_invite_enabled: true
discord_invite: "&c[BROADCAST]&f Replace this with a discord invite"
discord_interval_in_seconds: 240
reddragon_message_enabled: true
reddragon_message: "&c[BROADCAST]&f Replace this with the sponsorship"
reddragon_message_interval_in_seconds: 300
spawn_x: 0
spawn_y: 0
spawn_z: 0
spawn_yaw: 0
spawn_pitch: 0