name: OutlastMC Plugin
version: 1.0.0
main: io.github.diamondminer88.outlastmcplugin.OutlastMCPlugin

commands:
  respawn:
    description: Teleports you back to the spawnpoint
    usage: /respawn
  discord:
    description: Posts Discord invite
    usage: /discord